### GetUser
GET https://{{host}}:2000/chat/users/100
Accept: application/json

### SearchUsers
GET http://{{host}}:2000/chat/users/search/ali
Accept: application/json

### CreateUser
POST https://{{host}}:2000/chat/users
Content-Type: application/json

{
"name": "hu"
}

### DeleteUser
DELETE https://{{host}}:2000/chat/users/100
Content-Type: application/json

{
}

### Ask
POST https://{{host}}:2000/chat/users/100/ask
Content-Type: application/json

{
  "n": "42"
}


